image: ruby:2.3

variables:
    JEKYLL_ENV: production
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get -qq update && apt-get -qq install -y tor netcat
    - cat /etc/tor/torrc
    - bundle install
    - git submodule sync --recursive
    - git submodule foreach git pull origin master

test:
    stage: test
    script:
    - bundle exec jekyll build -d test
    artifacts:
        paths:
        - test
    except:
    - master

pages:
    stage: deploy
    script:
    - bundle exec jekyll build -d public
    artifacts:
        paths:
        - public
    only:
    - master
