image: ruby:2.3

variables:
    JEKYLL_ENV: production
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get -qq update && apt-get -qq install -y tor netcat openssh-server openssh-client
    - /etc/init.d/tor start
    - mkdir -p ~/.ssh && touch ~/.ssh/config
    - echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/deploy_key
    - echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    - echo "Host *.onion" >> ~/.ssh/config
    - echo "    ProxyCommand /usr/bin/nc -x localhost:9050 %h %p" >> ~/.ssh/config
    - echo "Listing home directory" && ls -la ~
    - echo "Listing SSH directory" && ls -la ~/.ssh
    - echo "Listing current working directory" && ls -la .
    - bundle install
    - git submodule sync --recursive
    - git submodule foreach git pull origin master

test:
    stage: test
    script:
    - bundle exec jekyll build -d test
    artifacts:
        paths:
        - test
    except:
    - master

pages:
    stage: deploy
    script:
    - bundle exec jekyll build -d public
    artifacts:
        paths:
        - public
    only:
    - master
