markdown: kramdown
paginate: 5
paginate_path: "/:num/"
title: "nolim1t.co :: thoughts become things"
description: "nolim1t.co is a tech blog about code and sometimes notable conferences that I'm following or attending"
url: "http://www.nolim1t.co"
author: "@nolim1t"
exclude: ["canary.sh", "generate.sh", "README.md", "LICENSE", ".git", "Gemfile", "Rakefile", "Gemfile.lock"]
gems:
  - jekyll-paginate
  - jekyll-feed
