name: CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        name: Checkout master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@1.0.0
      - uses: actions/setup-ruby@v1
        name: Run rakefile with ruby
        with:
          ruby-version: '2.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - run: rake
        name: Run Rakefile
